### ISSUE TITLE
Some humans love looking at PDF files, gerbers are usually consumed together

### ISSUE THREAD

**Issue by rusefillc** [corygrant/DingoPDM_HW#2]
Let me mix two pretty separate but a bit related minor usability issues

* fab houses usually needs gerbers.zip not individual files, even tools sometimes open gerbers.zip not individual file
* some humans love looking at PDFs without firing up proper KiCad to look at schematics

together see https://github.com/mck1117/proteus/tree/master/export/v0.1 as an example of a friendly "export/vX" approach for artifacts both gerbers, pdf and bill/placement

**Comment by corygrant** [comment]
Yea that's a good idea, I usually keep a folder with PDFs but I didn't have it in this folder. 
Closed with commit c598e04
